# Generated by Django 6.1.1 on 2026-10-03 23:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitter_email', models.EmailField(db_index=True, max_length=254)),
                ('submitter_name', models.CharField(max_length=120)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('original_filename', models.CharField(max_length=180)),
                ('stored_filename', models.CharField(max_length=80, unique=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('notification_error', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
