# Generated by Django 6.1.1 on 2026-10-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitlements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitlement',
            name='access_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='snipcart_order_token',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
    ]
