# Generated by Django 6.1.1 on 2026-09-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('biomedical-ai', 'Biomedical AI'), ('visual', 'Visual'), ('cancer', 'Cancer')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=240)),
                ('authors', models.CharField(max_length=300)),
                ('year', models.PositiveIntegerField()),
                ('doi', models.CharField(blank=True, max_length=80)),
                ('sku', models.CharField(max_length=80, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('abstract', models.TextField()),
                ('pdf_filename', models.CharField(help_text='File name inside frontend/public/papers/', max_length=160)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
    ]
