# Generated by Django 6.1.1 on 2026-10-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_paper_year_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='pdf_filename',
            field=models.CharField(help_text='File name inside backend/private_papers/', max_length=160),
        ),
    ]
