# Generated by Django 6.1.1 on 2026-10-03 23:59

from django.db import migrations, models

PLACEHOLDER_SLUGS = [
    "nilearn-image-paper",
    "uveal-melanoma",
    "diabetic-retinopathy",
    "lung-paper",
    "colon-cancer-paper",
]

GBM_KEYWORDS = [
    "glioblastoma",
    "co-expression",
    "gene network",
    "power-law",
    "Ramsey",
    "k-core",
    "signed-laplacian",
    "algebraic connectivity",
    "Benjamini-Hochberg",
    "NetworkX",
]


def drop_placeholder_papers(apps, schema_editor):
    Paper = apps.get_model("papers", "Paper")
    Paper.objects.filter(slug__in=PLACEHOLDER_SLUGS).delete()
    Paper.objects.filter(slug="gbm-signatures", keywords=[]).update(keywords=GBM_KEYWORDS)


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_purchase_file_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(drop_placeholder_papers, migrations.RunPython.noop),
    ]
