# Generated by Django 6.1.1 on 2026-10-03 23:59

from django.db import migrations, models

PLACEHOLDER_SLUGS = [
    "nilearn-image-paper",
    "uveal-melanoma",
    "diabetic-retinopathy",
    "lung-paper",
    "colon-cancer-paper",
]

GBM_KEYWORDS = [
    "glioblastoma",
    "co-expression",
    "gene network",
    "power-law",
    "Ramsey",
    "k-core",
    "signed-laplacian",
    "algebraic connectivity",
    "Benjamini-Hochberg",
    "NetworkX",
]


def drop_placeholder_papers(apps, schema_editor):
    Paper = apps.get_model("papers", "Paper")
    Paper.objects.filter(slug__in=PLACEHOLDER_SLUGS).delete()
    Paper.objects.update_or_create(
        slug="gbm-signatures",
        defaults={
            "category": "biomedical-ai",
            "title": "Biomedical Oncology Application of Gene Co-expression Networks in Glioblastoma Multiforme",
            "subtitle": "Four graph-theoretic signatures that separate glioblastoma networks from normal brain",
            "authors": "Adityakrishna SreeRamachandrarao, Anusha Lakshmi Dharmavathi, and Satyavathi Dronamraju",
            "year": None,
            "doi": "",
            "sku": "paper-gbm-signatures",
            "price": "29.00",
            "abstract": (
                "This paper treats glioblastoma as a network-level disorder rather than a short list of mutations. "
                "Four signatures separate the networks, including Ramsey substructure and the signed Laplacian spectrum."
            ),
            "keywords": GBM_KEYWORDS,
            "pdf_filename": "gene-co-expression-networks-in-glioblastoma-multiforme.pdf",
            "is_published": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_purchase_file_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(drop_placeholder_papers, migrations.RunPython.noop),
    ]
